### ISSUE TITLE
kubuntu 25.04 compilation failed

### ISSUE THREAD

**Issue by Blad3forc3** [pedgarcia/fujisan#4]
Hi i'm getting no sound on the emulator with kubuntu 25.04

when compiling it errors:

=== Fujisan Build System ===
→ Version: v1.0.1-20-g592669d
→ Platform: linux

=== Building Linux ===
=== Linux Build for Fujisan ===
→ Using container runtime: docker
→ Project root: /media/ade/Temp/fujisan
→ Version: v1.0.1-20-g592669d

=== Building Container Image ===
→ Building Ubuntu 24.04 based container for x86_64...
[+] Building 83.2s (7/7) FINISHED                                                                                                           docker:default
 => [internal] load build definition from Dockerfile.ubuntu-24.04                                                                                     0.0s
 => => transferring dockerfile: 1.17kB                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/ubuntu:24.04                                                                                       1.6s
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [1/3] FROM docker.io/library/ubuntu:24.04@sha256:7c06e91f61fa88c08cc74f7e1b7c69ae24910d745357e0dfe1d2c0322aaf20f9                                 2.0s
 => => resolve docker.io/library/ubuntu:24.04@sha256:7c06e91f61fa88c08cc74f7e1b7c69ae24910d745357e0dfe1d2c0322aaf20f9                                 0.0s
 => => sha256:7c06e91f61fa88c08cc74f7e1b7c69ae24910d745357e0dfe1d2c0322aaf20f9 6.69kB / 6.69kB                                                        0.0s
 => => sha256:35f3a8badf2f74c1b320a643b343536f5132f245cbefc40ef802b6203a166d04 424B / 424B                                                            0.0s
 => => sha256:e0f16e6366fef4e695b9f8788819849d265cde40eb84300c0147a6e5261d2750 2.29kB / 2.29kB                                                        0.0s
 => => sha256:b71466b94f266b4c2e0881749670e5b88ab7a0fd4ca4a4cdf26cb45e4bde7e4e 29.72MB / 29.72MB                                                      1.0s
 => => extracting sha256:b71466b94f266b4c2e0881749670e5b88ab7a0fd4ca4a4cdf26cb45e4bde7e4e                                                             0.8s
 => [2/3] RUN apt-get update && apt-get install -y     build-essential     cmake     git     pkg-config     libtool     autoconf     automake     l  73.1s
 => [3/3] WORKDIR /build                                                                                                                              0.1s
 => exporting to image                                                                                                                                6.3s
 => => exporting layers                                                                                                                               6.3s
 => => writing image sha256:f5c4a5b3fb56cbc8416db6479fa3eeae8d8d00da57979f288ce14e469e66cfa6                                                          0.0s
 => => naming to docker.io/library/fujisan-linux-builder:ubuntu24                                                                                     0.0s
✓ Container image built
=== Building Fujisan in Container ===
→ Running build for version v1.0.1-20-g592669d on x86_64...
Building Fujisan version v1.0.1-20-g592669d...
-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SDL2 not found - using Qt audio backend only
-- === Fujisan Build Configuration ===
-- Project Version: 1.0.0
-- Qt5 Path: /opt/homebrew/opt/qt@5/lib/cmake
-- Build Type: Release
-- libatari800 will be built automatically as external project
-- No ATARI800_SRC_PATH environment variable required
-- =====================================
-- Configuring done (0.4s)
-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    FUJISAN_VERSION

-- Build files have been written to: /tmp/fujisan-build/build-release
Building with 4 cores...
[  3%] Creating directories for 'atari800_external'
[  6%] Performing download step (git clone) for 'atari800_external'
-- atari800_external download command succeeded.  See also /tmp/fujisan-build/build-release/atari800_external-prefix/src/atari800_external-stamp/atari800_external-download-*.log
[  9%] Performing update step for 'atari800_external'
-- atari800_external update command succeeded.  See also /tmp/fujisan-build/build-release/atari800_external-prefix/src/atari800_external-stamp/atari800_external-update-*.log
[ 12%] Performing patch step for 'atari800_external'
-- atari800_external patch command succeeded.  See also /tmp/fujisan-build/build-release/atari800_external-prefix/src/atari800_external-stamp/atari800_external-patch-*.log
[ 15%] Performing configure step for 'atari800_external'
-- atari800_external configure command succeeded.  See also /tmp/fujisan-build/build-release/atari800_external-prefix/src/atari800_external-stamp/atari800_external-configure-*.log
[ 18%] Performing build step for 'atari800_external'
-- atari800_external build command succeeded.  See also /tmp/fujisan-build/build-release/atari800_external-prefix/src/atari800_external-stamp/atari800_external-build-*.log
[ 21%] No install step for 'atari800_external'
[ 25%] Completed 'atari800_external'
[ 25%] Built target atari800_external
[ 25%] Built target Fujisan_autogen_timestamp_deps
[ 28%] Automatic MOC for target Fujisan
[ 28%] Built target Fujisan_autogen
[ 34%] Building CXX object CMakeFiles/Fujisan.dir/src/emulatorwidget.cpp.o
[ 34%] Building CXX object CMakeFiles/Fujisan.dir/src/mainwindow.cpp.o
[ 37%] Building CXX object CMakeFiles/Fujisan.dir/src/main.cpp.o
[ 40%] Building CXX object CMakeFiles/Fujisan.dir/Fujisan_autogen/mocs_compilation.cpp.o
In file included from /tmp/fujisan-build/build-release/atari800-src/src/devices.h:5,
                 from /tmp/fujisan-build/build-release/Fujisan_autogen/6YEA5652QU/../../../include/atariemulator.h:100,
                 from /tmp/fujisan-build/build-release/Fujisan_autogen/6YEA5652QU/moc_atariemulator.cpp:10,
                 from /tmp/fujisan-build/build-release/Fujisan_autogen/mocs_compilation.cpp:2:
/tmp/fujisan-build/build-release/atari800-src/src/atari.h:31: warning: "ULONG" redefined
   31 | #define ULONG unsigned int
      | 
In file included from /tmp/fujisan-build/build-release/Fujisan_autogen/6YEA5652QU/../../../include/atariemulator.h:40:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/libatari800.h:14: note: this is the location of the previous definition
   14 | #define ULONG uint32_t
      | 
In file included from /tmp/fujisan-build/build-release/atari800-src/src/devices.h:5,
                 from /tmp/fujisan-build/include/atariemulator.h:100,
                 from /tmp/fujisan-build/include/mainwindow.h:28,
                 from /tmp/fujisan-build/src/mainwindow.cpp:12:
/tmp/fujisan-build/build-release/atari800-src/src/atari.h:31: warning: "ULONG" redefined
   31 | #define ULONG unsigned int
      | 
In file included from /tmp/fujisan-build/include/atariemulator.h:40:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/libatari800.h:14: note: this is the location of the previous definition
   14 | #define ULONG uint32_t
      | 
In file included from /tmp/fujisan-build/build-release/atari800-src/src/devices.h:5,
                 from /tmp/fujisan-build/include/atariemulator.h:100,
                 from /tmp/fujisan-build/include/mainwindow.h:28,
                 from /tmp/fujisan-build/src/main.cpp:14:
/tmp/fujisan-build/build-release/atari800-src/src/atari.h:31: warning: "ULONG" redefined
   31 | #define ULONG unsigned int
      | 
In file included from /tmp/fujisan-build/include/atariemulator.h:40:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/libatari800.h:14: note: this is the location of the previous definition
   14 | #define ULONG uint32_t
      | 
In file included from /tmp/fujisan-build/build-release/atari800-src/src/devices.h:5,
                 from /tmp/fujisan-build/include/atariemulator.h:100,
                 from /tmp/fujisan-build/include/emulatorwidget.h:20,
                 from /tmp/fujisan-build/src/emulatorwidget.cpp:8:
/tmp/fujisan-build/build-release/atari800-src/src/atari.h:31: warning: "ULONG" redefined
   31 | #define ULONG unsigned int
      | 
In file included from /tmp/fujisan-build/include/atariemulator.h:40:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/libatari800.h:14: note: this is the location of the previous definition
   14 | #define ULONG uint32_t
      | 
/tmp/fujisan-build/include/atariemulator.h:118:17: error: conflicting declaration of C function 'void LIBATARI800_StateLoad(unsigned char*, statesav_tags_t*)'
  118 |     extern void LIBATARI800_StateLoad(unsigned char *buffer, statesav_tags_t *tags);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/fujisan-build/include/atariemulator.h:104:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/statesav.h:16:6: note: previous declaration 'void LIBATARI800_StateLoad(unsigned char*)'
   16 | void LIBATARI800_StateLoad(UBYTE *buffer);
      |      ^~~~~~~~~~~~~~~~~~~~~
/tmp/fujisan-build/build-release/Fujisan_autogen/6YEA5652QU/../../../include/atariemulator.h:118:17: error: conflicting declaration of C function 'void LIBATARI800_StateLoad(unsigned char*, statesav_tags_t*)'
  118 |     extern void LIBATARI800_StateLoad(unsigned char *buffer, statesav_tags_t *tags);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/fujisan-build/build-release/Fujisan_autogen/6YEA5652QU/../../../include/atariemulator.h:104:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/statesav.h:16:6: note: previous declaration 'void LIBATARI800_StateLoad(unsigned char*)'
   16 | void LIBATARI800_StateLoad(UBYTE *buffer);
      |      ^~~~~~~~~~~~~~~~~~~~~
/tmp/fujisan-build/include/atariemulator.h:118:17: error: conflicting declaration of C function 'void LIBATARI800_StateLoad(unsigned char*, statesav_tags_t*)'
  118 |     extern void LIBATARI800_StateLoad(unsigned char *buffer, statesav_tags_t *tags);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/fujisan-build/include/atariemulator.h:104:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/statesav.h:16:6: note: previous declaration 'void LIBATARI800_StateLoad(unsigned char*)'
   16 | void LIBATARI800_StateLoad(UBYTE *buffer);
      |      ^~~~~~~~~~~~~~~~~~~~~
/tmp/fujisan-build/include/atariemulator.h:118:17: error: conflicting declaration of C function 'void LIBATARI800_StateLoad(unsigned char*, statesav_tags_t*)'
  118 |     extern void LIBATARI800_StateLoad(unsigned char *buffer, statesav_tags_t *tags);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/fujisan-build/include/atariemulator.h:104:
/tmp/fujisan-build/build-release/atari800-src/src/libatari800/statesav.h:16:6: note: previous declaration 'void LIBATARI800_StateLoad(unsigned char*)'
   16 | void LIBATARI800_StateLoad(UBYTE *buffer);
      |      ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/Fujisan.dir/build.make:124: CMakeFiles/Fujisan.dir/src/emulatorwidget.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Fujisan.dir/build.make:82: CMakeFiles/Fujisan.dir/Fujisan_autogen/mocs_compilation.cpp.o] Error 1
make[2]: *** [CMakeFiles/Fujisan.dir/build.make:96: CMakeFiles/Fujisan.dir/src/main.cpp.o] Error 1
make[2]: *** [CMakeFiles/Fujisan.dir/build.make:110: CMakeFiles/Fujisan.dir/src/mainwindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/Fujisan.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
ERROR: Build failed

**Comment by pedgarcia** [comment]
Hi ,

thanks for the info. I had some problems with Linux - For a while was just "theoretical" since I didn't have a Linux distro to actually test it. 

Could you please try the new v1.0.4? This one .tar.gz should work on (k)ubuntu 25.04 as well as the compilation. FYI, I am building it using a docker container, so if you are building it natively we might need to find out the differences.

I will continue working on making the linux version better.

Thanks

Paulo

**Comment by pedgarcia** [comment]
Hi @minagra I believe the audio will be perfect when I release v1.0.5. I just need to run more tests.

**Comment by pedgarcia** [comment]
Hey @Blad3forc3 , thanks for testging. 

I think I forgot to add the most essential change to the tar file. Can you try this please?

Create fujisan-portable/bin/qt.conf file with the content:
```
  [Paths]
  Plugins = ../plugins
```

This should be enough to make it work? If you can confirm I will update the tarballs

thanks again

Paulo

**Comment by minagra** [comment]
Let me look into the compilation failure for you as well, @pedgarcia . I can spin up a bare-metal Kubuntu instance and have a go at reproducing the issue.

Is there a concept of assigning bugs in GitHub? If so, please assign this one to me.

**Comment by pedgarcia** [comment]
Thanks @minagra . It is assigned to you! FYI, because I compile all 3 versions on my Mac, I am using docker (actually podman) to build them. 

In the future, I could probably detect the host and perform a native compilation in that case. That should speed up things for Linux users in case they just want that version anyways.

Cheers

Paulo

**Comment by minagra** [comment]
Kubuntu 25.04 is no longer obviously offered for download at https://kubuntu.org/getkubuntu/

It's been replaced by 25.10. Nonetheless 25.04 is available from https://cdimage.ubuntu.com/kubuntu/releases/25.04/release/, which can be navigated to from the link above.

I'm downloading this now and I'll install it shortly on a 2013 Thinkpad T410 with a 4 core i5 M520 and 4GB RAM.

**Comment by minagra** [comment]
@Blad3forc3 do you keep your 25.04 Kubuntu up to date? Pretty much every session at any Linux machine, I run `sudo apt get update && sudo apt get upgrade -y && sudo apt autoremove -y`. I'm doing that now with the Kubuntu instance I've got running on my old Thinkpad before trying @pedgarcia 's latest changes.

Okay, that was successful! TL;DR:

```
$ ls -ltrh /home/ben/src/fujisan/dist/linux
total 103M
-rw-r--r-- 1 ben ben 31M Oct 30 16:09 fujisan_1.0.5-11-g3f10c2d_amd64.deb
-rw-r--r-- 1 ben ben 102 Oct 30 16:09 fujisan_1.0.5-11-g3f10c2d_amd64.deb.sha256
-rw-r--r-- 1 ben ben 72M Oct 30 16:09 fujisan-1.0.5-11-g3f10c2d-linux-x64.tar.gz
-rw-r--r-- 1 ben ben 109 Oct 30 16:09 fujisan-1.0.5-11-g3f10c2d-linux-x64.tar.gz.sha256
``` 
Thank you for these changes, @pedgarcia !

The full story:

```
$ cd ~/src
$ rm -rf fujisan/
$ git clone https://github.com/pedgarcia/fujisan.git
$ cd fujisan/
$ ./build.sh linux
```
Some time passes...
```
Build completed successfully!
✓ Linux build completed
=== Copying to Distribution Directory ===
✓ Copied .deb package to dist/
✓ Copied .tar.gz package to dist/
→ Removing container image...
Untagged: fujisan-linux-builder:ubuntu22-amd64
Deleted: sha256:1d448d04a986fb7ed0c635febc39ffe396eb4f7fa63189419292d8c7f44c5386
=== Build Summary ===
✓ Linux build completed successfully!

Architecture: amd64
Version: v1.0.5-11-g3f10c2d
Output files in /home/ben/src/fujisan/dist/linux:
  • fujisan_1.0.5-11-g3f10c2d_amd64.deb (31M) - Debian/Ubuntu package
  • fujisan-1.0.5-11-g3f10c2d-linux-x64.tar.gz (72M) - Portable package

Installation:
  Debian/Ubuntu: sudo dpkg -i fujisan_1.0.5-11-g3f10c2d_amd64.deb
  Portable: tar xzf fujisan-1.0.5-11-g3f10c2d-linux-x64.tar.gz && ./fujisan-portable/fujisan.sh
✓ Linux build complete

=== Build Summary ===
✓ Build complete for: linux

Distribution files:
  Linux (dist/linux/):
    - /home/ben/src/fujisan/dist/linux/fujisan_1.0.5-11-g3f10c2d_amd64.deb (31M)
    - /home/ben/src/fujisan/dist/linux/fujisan-1.0.5-11-g3f10c2d-linux-x64.tar.gz (72M)


To build for other platforms, run:
  ./build.sh [platform] --clean
```
